Baikal + yocto 2.1
Change-Id: I0400b1acab5aec87434d9ccf6e9055e9dca8b4c9

diff --git a/yocto/poky/scripts/oe-setup-builddir b/yocto/poky/scripts/oe-setup-builddir
--- a/yocto/poky/scripts/oe-setup-builddir
+++ b/yocto/poky/scripts/oe-setup-builddir
@@ -61,7 +61,7 @@ if [ -n "$TEMPLATECONF" ]; then
             TEMPLATECONF="$OEROOT/$TEMPLATECONF"
         fi
         if [ ! -d "$TEMPLATECONF" ]; then
-            echo >&2 "Error: TEMPLATECONF value points to nonexistent directory '$TEMPLATECONF'"
+            echo >&2 "Error: '$TEMPLATECONF' must be a directory containing local.conf & bblayers.conf"
             exit 1
         fi
     fi
